name:                applied-haskell
version:             0.1.0.0
github:              "TimWSpence/applied-haskell"
license:             BSD3
author:              "Tim Spence"
maintainer:          "timothywspence@gmail.com"
copyright:           "2019 Tim Spence"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/applied-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- rio

library:
  source-dirs: src

executables:
  applied-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - applied-haskell

tests:
  applied-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - applied-haskell
